export const text_en = {
  stockLoaded: 'Shop stock decoded from the original ROM is ready.',
  stockOnly:
    'The stock list is ready. Exact shop and entrance map positions are not available in this data yet.',
  loadFailed: 'Shop stock could not be loaded.',
  retryLoad: 'Retry this shop search',
  backToSource: 'Return to the previous page',
  openCatalogue: 'Open the item catalogue',
  recoveryActions: 'Recovery actions',
  area: (n) => `Fishing area ${n}`,
  outdoor: (n) => `Area ${n} · town entrances`,
  town: (n) => `Area ${n} · seller positions`,
  townSummary: (n) => `Fishing area ${n} · paired town interior`,
  mapSetEvidence: (place, n) =>
    `${place === 'outdoor' ? 'Outdoor field' : 'Town interior'} · map set ${n}`,
  fieldHeading: 'Which town entrance?',
  townHeading: 'Which shop / entrance?',
  focusedEntrance: (n) => `Showing only entrance ${n + 1}, linked to this shop.`,
  mapUnavailable: 'No ROM-rendered terrain image is available for this map set.',
  invalidPoints:
    'Some decoded positions fall outside the valid map bounds. Those markers are hidden instead of guessed.',
  noValidPoint: 'No valid map position is available for this area. No location is guessed.',
  fullMap: 'Open the full terrain image ↗',
  noLocations:
    'Stock is confirmed for this area, but the exact shop position and entrances are not present in the available location data.',
  mapNoEntrances:
    'No field-to-town entrances are recorded for this area in the available location data.',
  entrance: (n) => `Entrance ${n + 1}`,
  outside: 'Field entrance',
  arrival: 'Town arrival',
  regular: 'Regular equipment shop',
  special: 'Special rod seller',
  unclassified: 'Other interaction (not identified as a shop)',
  shopPoint: 'Seller location',
  coord: (x, y) => `Tile X ${x}, Y ${y}`,
  pairNote:
    'The two points are a verified field entrance and its paired town arrival. No walking route inside the town is implied.',
  endpointNote:
    'The ROM identifies this shop interaction point. The walking route from an entrance has not been verified.',
  linkedEntrance: (n, arrival) =>
    `Enter through entrance ${n + 1} (arrival at ${arrival.x}, ${arrival.y}). An original-ROM probe opened this seller from that arrival point; the route from other outdoor positions is not verified.`,
  openEntrance: 'Show this entrance on the field map ↗',
  viewOffers: 'See what this shop sells ↓',
  testedInputs: 'Tested controller inputs',
  openTownArrival: 'Show paired town arrival ↗',
  regularNote: 'This interaction opens the regular item category and purchase menu.',
  specialNote: 'This interaction opens a fixed selection of special rods.',
  filtered: (n) => `${n} matching offer${n === 1 ? '' : 's'}`,
  targetFound: 'This item is sold in the selected area.',
  targetNotHere: 'This item is not listed for sale in the selected area.',
  soldElsewhere: 'Recorded sale areas:',
  soldConditional:
    'This offer is conditional. Follow the unlock steps on the card before looking for it in the shop.',
  none: 'No offers match these filters.',
  noCategory: 'No matching items are listed for this area and item type.',
  noTarget: 'This ID is not in the item catalogue.',
  browseArea: (n) => `Show Area ${n}`,
  categoryAll: 'All item types',
  types: {
    rod: 'Fishing rods',
    lure: 'Lures',
    hook: 'Hooks',
    float_weight: 'Floats and sinkers',
    bait: 'Bait',
    fly: 'Ready-made flies',
    fly_wing: 'Fly wings in ready-made bundles',
    fly_tail: 'Fly tails in ready-made bundles',
    food: 'Food',
    general_tool: 'Tools and quest items',
  },
  targetBadge: 'Selected item',
  component: 'Open item details',
  bundle: 'Ready-made fly bundle',
  complete: 'Complete bundle price',
  parts: 'Parts in this set',
  included: 'Included in this ready-made bundle',
  conditionTitle: 'How to unlock this offer',
  ayu: 'Sell at least one Ayu from your keepnet first. The decoy-Ayu offer then appears in the Area 3 shop. Buying it fills the stack to 9 and subtracts 9 from the sold-Ayu counter (down to 0). If it disappears again, sell more Ayu before trying again.',
  ayuFish: 'Find Ayu fishing spots ↗',
  noPrice: 'No separate price confirmed',
  price: (n) => `¥${n}`,
  foodRecovery: (hp) => `Restores up to ${hp} HP`,
  returnItem: '← Back to the page that opened this shop',
  returnCatalogue: '← Item catalogue',
  technical: 'ROM evidence',
  evidenceStock:
    'The offers below come from the decoded six-area ROM stock arrays. A basic item price alone is not treated as proof that a shop sells it.',
  evidenceBundles:
    'Fly body, wing and tail entries are decoded as a single ready-made bundle. The listed price is the total bundle quote; parts are not separate offers here.',
  evidenceLocations:
    'Map pins mark decoded field-to-town transitions and shop interaction points. An interaction point does not establish a walking route.',
  source: 'Source record',
  entranceOrdinal: 'Entrance index',
  kind: 'Verified role',
  mode: 'Raw interaction mode',
  slot: 'ROM slot',
  stageWord: (n) => `Area ${n}`,
  warningLocations:
    'Shop stock is available, but map positions could not be loaded. The page does not guess where to walk.',
  language: 'Language',
}
