export const text_ja = {
  stockLoaded: 'オリジナルROMから解析した販売品を読み込みました。',
  stockOnly: '販売品は読み込めました。店や入口の正確な位置は、現在のデータでは確認できません。',
  loadFailed: '販売品データを読み込めませんでした。',
  retryLoad: '同じ条件でもう一度読み込む',
  backToSource: '開く前のページに戻る',
  openCatalogue: 'アイテム一覧を開く',
  recoveryActions: '読み込み失敗時の操作',
  area: (n) => `釣りエリア${n}`,
  outdoor: (n) => `エリア${n} · 町の入口`,
  town: (n) => `エリア${n} · 店の位置`,
  townSummary: (n) => `釣りエリア${n} · 対応する町の中`,
  mapSetEvidence: (place, n) =>
    `${place === 'outdoor' ? '屋外フィールド' : '町の中'} · マップセット${n}`,
  fieldHeading: 'どの入口から町へ？',
  townHeading: 'どの店・入口へ？',
  focusedEntrance: (n) => `この店に対応する入口${n + 1}を表示しています。`,
  mapUnavailable: 'このマップセットのROM地形画像はありません。',
  invalidPoints:
    '解析された座標の一部が有効なマップ範囲外のため、位置を推測せずマーカーを非表示にしました。',
  noValidPoint: 'このエリアに有効なマップ座標がありません。位置は推測しません。',
  fullMap: '地形全体の画像を開く ↗',
  noLocations:
    'このエリアの販売品は確認できましたが、現在の位置データに店や入口の正確な位置はありません。',
  mapNoEntrances: '現在の位置データに、このエリアから町への入口は記録されていません。',
  entrance: (n) => `入口${n + 1}`,
  outside: '屋外の入口',
  arrival: '町側の到着地点',
  regular: '通常の釣り道具店',
  special: '特別な竿の販売所',
  unclassified: 'その他の操作地点（店とは未確認）',
  shopPoint: '店の場所',
  coord: (x, y) => `タイル X ${x}, Y ${y}`,
  pairNote:
    'この2地点はROMで対応関係を確認した屋外入口と町側の到着地点です。町の中の徒歩ルートを示すものではありません。',
  endpointNote: 'ROMで店の操作地点を確認しました。入口からの徒歩ルートは未確認です。',
  linkedEntrance: (n, arrival) =>
    `入口${n + 1}から町に入り（到着タイル ${arrival.x}, ${arrival.y}）、店のマーカーへ進みます。オリジナルROMのテストで、この到着地点から店のメニューが開くことを確認しました。屋外の他の場所から入口までの道順は確認していません。`,
  openEntrance: 'この入口をフィールドマップで見る ↗',
  viewOffers: 'この店の販売品を見る ↓',
  testedInputs: 'テスト時のボタン入力',
  openTownArrival: '対応する町の到着地点を見る ↗',
  regularNote: '通常のアイテムカテゴリと購入メニューを開く地点です。',
  specialNote: '固定された特別な竿の一覧を開く地点です。',
  filtered: (n) => `該当する販売品：${n}件`,
  targetFound: '選択したエリアで販売されています。',
  targetNotHere: '選択したエリアの販売品には含まれていません。',
  soldElsewhere: '販売記録のあるエリア：',
  soldConditional: 'この品には購入条件があります。店を探す前にカードの解放手順を確認してください。',
  none: '条件に一致する販売品はありません。',
  noCategory: 'このエリアに一致する種類のアイテムはありません。',
  noTarget: 'このIDはアイテム一覧にありません。',
  browseArea: (n) => `エリア${n}を見る`,
  categoryAll: 'すべての種類',
  types: {
    rod: '釣り竿',
    lure: 'ルアー',
    hook: '針',
    float_weight: 'ウキ・オモリ',
    bait: 'エサ',
    fly: '完成品の毛バリ',
    fly_wing: '完成品セットのウィング',
    fly_tail: '完成品セットのテール',
    food: '食料',
    general_tool: '道具・クエストアイテム',
  },
  targetBadge: '選択したアイテム',
  component: 'アイテム詳細を開く',
  bundle: '完成品の毛バリセット',
  complete: 'セット価格',
  parts: 'セットの構成品',
  included: 'この完成品セットに含まれます',
  conditionTitle: '購入条件を満たす方法',
  ayu: 'まずびくからアユを1匹以上売ってください。おとりアユがエリア3の店に表示されます。購入すると所持数が9個になり、売却アユ数カウンターが9減ります（0未満にはなりません）。再び消えたら、追加でアユを売ってください。',
  ayuFish: 'アユの釣り場を見る ↗',
  noPrice: '個別の販売価格は未確認',
  price: (n) => `${n}円`,
  foodRecovery: (hp) => `最大${hp} HP回復`,
  returnItem: '← 店を開いたページに戻る',
  returnCatalogue: '← アイテム一覧',
  technical: 'ROMの根拠',
  evidenceStock:
    '以下の品は、ROMから解析した6エリア分の販売在庫に基づきます。アイテムの基本価格欄だけでは店頭販売を確認したことにはなりません。',
  evidenceBundles:
    '毛バリのボディ・ウィング・テールは一つの完成品セットとして解析しています。表示価格はセット全体の見積額で、各部品を別商品として表示していません。',
  evidenceLocations:
    'マーカーはROMから解析したエリア間の移動地点と店の操作地点を示します。操作地点から徒歩ルートまでは分かりません。',
  source: '根拠レコード',
  entranceOrdinal: '入口番号',
  kind: '確認済みの店の役割',
  mode: 'ROM操作モード',
  slot: 'ROMスロット',
  stageWord: (n) => `エリア${n}`,
  warningLocations:
    '販売品は読み込めましたが、地図上の位置を読み込めません。徒歩ルートは推測しません。',
  language: '言語',
}
