export const copy = {
  th: {
    title: 'เควสต์และการแลกของ',
    intro: 'เลือกด่านเพื่อดูสิ่งที่ต้องทำ ของที่ต้องเก็บไว้ และทางไปต่อ จากข้อมูลที่ตรวจยืนยันแล้ว',
    scope: 'หน้านี้รวมข้อค้นพบที่ยืนยันแล้ว ยังไม่ใช่รายการเควสต์ทั้งหมดของเกม',
    area: 'ด่าน',
    story: 'เนื้อเรื่องและทางไปต่อ',
    exchange: 'แลกของ',
    optional: 'ของเสริมและหีบ',
    evidence: 'หลักฐานและข้อจำกัด',
    empty: 'ยังไม่มีการกระทำที่ยืนยันสำหรับด่านนี้',
    ready: (area, count) => `ด่าน ${area} · ${count} รายการที่ยืนยัน`,
    loading: 'กำลังโหลดข้อมูลที่ยืนยัน…',
    failed: 'โหลดข้อมูลไม่สำเร็จ',
    retry: 'ลองอีกครั้ง',
    back: '← กลับหน้าที่มา',
    catalogue: '← เลือกอุปกรณ์',
  },
  en: {
    title: 'Quests and exchanges',
    intro:
      'Choose an area to find what to do, what to keep and where to go next, from verified findings.',
    scope: 'Verified findings only; this is not a complete list of every quest in the game.',
    area: 'Area',
    story: 'Story and next steps',
    exchange: 'Exchanges',
    optional: 'Optional items and chests',
    evidence: 'Evidence and limits',
    empty: 'No verified actions are listed for this area yet.',
    ready: (area, count) => `Area ${area} · ${count} verified actions`,
    loading: 'Loading verified findings…',
    failed: 'Could not load the findings.',
    retry: 'Try again',
    back: '← Back to source',
    catalogue: '← Choose equipment',
  },
  ja: {
    title: 'クエストと交換',
    intro:
      'エリアを選び、何をするか、何を残すか、次にどこへ行くかを確認できます。確認済みの調査結果に基づきます。',
    scope: '確認済みの結果を掲載しています。ゲーム内の全クエスト一覧ではありません。',
    area: 'エリア',
    story: '物語と次の行動',
    exchange: '交換',
    optional: '任意のアイテムと宝箱',
    evidence: '根拠と制限',
    empty: 'このエリアには確認済みの行動がまだ掲載されていません。',
    ready: (area, count) => `エリア${area}・確認済み${count}件`,
    loading: '確認済みの結果を読み込み中…',
    failed: '読み込めませんでした。',
    retry: '再試行',
    back: '← 元のページへ',
    catalogue: '← 装備を選ぶ',
  },
}
