export const c_en = {
  area: (n) => `Area ${n}`,
  areas: 'areas',
  areasPrefix: 'Areas',
  fish: 'fish',
  fishIn: 'Fish in this area',
  searchResults: 'Search results across all areas',
  showAll: 'Show all fish',
  clearSearch: 'Clear search',
  noFish: 'No fish match this search.',
  noArea: 'This fish has no configured point in this area. Choose one of its available areas.',
  noTarget: 'No fish target selected. Map shows all species in this section.',
  selectedTarget: 'Map shows only',
  section: 'Section',
  spots: 'configured points',
  species: 'species',
  shared: 'fish share this tile',
  targetAvailable: 'target here',
  targetAbsent: 'target absent',
  allArea: (n) => `${n} fish`,
  fullMap: 'Area terrain from the ROM',
  tackle: 'See this fish’s compatible tackle ↗',
  noPoint: 'No configured points in this section.',
  mapSection: (col, row) => `Column ${col}, row ${row}`,
  fishName: (id) => `Fish ${id}`,
  point: (n) => `${n} unique point${n === 1 ? '' : 's'}`,
  notFound: 'Not found in this area',
  romName: 'ROM fish',
  back: 'Equipment catalogue',
}
