export const c_ja = {
  area: (n) => `エリア${n}`,
  areas: 'エリア',
  areasPrefix: 'エリア',
  fish: '種',
  fishIn: 'このエリアの魚',
  searchResults: '全エリアの検索結果',
  showAll: '魚をすべて表示',
  clearSearch: '検索をクリア',
  noFish: '一致する魚が見つかりません。',
  noArea: 'この魚は選択中エリアに出現設定がありません。出現するエリアを選んでください。',
  noTarget: '魚を選択していません。この範囲の全魚種を表示します。',
  selectedTarget: '表示中:',
  section: 'マップ範囲',
  spots: '設定地点',
  species: '魚種',
  shared: '魚が同じタイルを共有',
  targetAvailable: '対象あり',
  targetAbsent: '対象なし',
  allArea: (n) => `${n}種`,
  fullMap: 'ROMから復元した地形',
  tackle: 'この魚に使える道具を見る ↗',
  noPoint: 'この範囲に設定地点はありません。',
  mapSection: (col, row) => `列${col}・行${row}`,
  fishName: (id) => `魚 ${id}`,
  point: (n) => `${n}地点`,
  notFound: 'このエリアに地点なし',
  romName: 'ROMの魚名',
  back: '道具カタログ',
}
