export const c_th = {
  area: (n) => `ด่าน ${n}`,
  areas: 'ด่าน',
  areasPrefix: 'ด่าน',
  fish: 'ชนิด',
  fishIn: 'ปลาในด่านนี้',
  searchResults: 'ผลค้นหาปลาจากทุกด่าน',
  showAll: 'แสดงปลาทั้งหมด',
  clearSearch: 'ล้างคำค้น',
  noFish: 'ไม่พบปลาที่ตรงกับคำค้น',
  noArea: 'ปลาเป้าหมายไม่มีจุดที่ตั้งไว้ในด่านนี้ เลือกด่านที่มีปลาได้',
  noTarget: 'ยังไม่ได้เลือกปลา แผนที่แสดงปลาทุกชนิดในส่วนนี้',
  selectedTarget: 'แผนที่แสดงเฉพาะ',
  section: 'ส่วนแผนที่',
  spots: 'จุดที่ตั้งไว้',
  species: 'ชนิด',
  shared: 'ปลาหลายชนิดใช้ช่องนี้ร่วมกัน',
  targetAvailable: 'มีปลาเป้าหมาย',
  targetAbsent: 'ไม่มีปลาเป้าหมาย',
  allArea: (n) => `ปลา ${n} ชนิด`,
  fullMap: 'ภาพฉากจาก ROM',
  tackle: 'ดูอุปกรณ์ที่ใช้กับปลานี้ ↗',
  noPoint: 'ไม่มีจุดในส่วนแผนที่นี้',
  mapSection: (col, row) => `คอลัมน์ ${col} แถว ${row}`,
  fishName: (id) => `ปลา ${id}`,
  point: (n) => `${n} จุด`,
  notFound: 'ไม่มีจุดในด่านนี้',
  romName: 'ชื่อปลาใน ROM',
  back: 'คู่มืออุปกรณ์',
}
