export const copy_ja = {
  allItems: '道具一覧を見る',
  back: '← 前のページへ戻る',
  invalidTitle: '道具が見つかりません',
  invalidBody: '道具IDがないか、カタログに登録されていません。',
  loadErrorTitle: '道具の詳細を読み込めませんでした',
  loadErrorBody:
    '道具データを読み込めないか、表示できません。もう一度試すか、道具一覧に戻ってください。',
  retryLoad: 'このページを再読み込み',
  backToCatalogue: '道具一覧へ戻る',
  category: 'カテゴリ',
  itemId: '道具ID',
  use: 'この道具の使い方',
  details: '使い方と注意点',
  shop: '入手場所',
  shopArea: (n) => `エリア${n}`,
  price: (n) => `${n}円`,
  priceFromRom: 'ROM内の価格欄',
  stockAt: '下記エリアの在庫記録',
  bundleAt: (n) => `エリア${n}の店売り毛バリセット`,
  noShop: '現在のROMデータでは、この道具の店頭在庫を確認できません。',
  shopMap: '販売店を見る',
  mapNote:
    '店のページで町への入口、店員の位置、在庫を確認できます。屋外と町内のマップは別々に表示します。',
  unlock: 'この品を買えるようにするには：',
  ayuOffer:
    'びくからアユを1匹以上売ると、おとりアユがエリア3の店に表示されます。購入すると所持数が9個になり、売却アユ数のカウンターが9減ります（0未満にはなりません）。表示から消えたら、追加でアユを売ってください。',
  unknownShopCondition: 'この商品には追加の購入条件がありますが、内容はまだ確認できていません。',
  noShopMap: 'ROMデータに使用・販売エリアの記録がありません。',
  fish: 'この道具の判定を通る魚',
  fishScope: 'この判定を通っても、食いつきや取り込みは保証されません。',
  routeFloat: 'ウキ仕掛け',
  routeSinker: 'オモリ仕掛け',
  floatFishHeading: 'ウキ釣りの魚プロフィール一覧',
  floatFishSummary: 'ウキ釣りの魚を見る',
  floatTargetYes:
    'この魚はウキ釣りの一覧に含まれる。ウキ型ごとの魚判定はないため、この魚が受け付けるエサを選ぶ。',
  floatTargetNo: 'この魚は記録されたウキ釣りの一覧に含まれない。',
  floatFishScope:
    'ウキID 01–08は同じウキ釣り判定を使い、型ごとの魚ボーナスや制限はない。一覧は食いつきや釣り上げを保証しない。',
  sinkerFishHeading: 'オモリ釣りの追加プロフィール判定を通る魚',
  sinkerFishSummary: 'オモリ釣りの魚を見る',
  sinkerTargetYes:
    'この魚はオモリ釣りの追加判定を通る一覧に含まれる。選んだエサもこの魚の条件を通る必要がある。',
  sinkerTargetNo: 'この魚は記録されたオモリ釣りの通過一覧に含まれない。',
  sinkerFishScope:
    'オモリID 09–0Aは同じ追加プロフィール判定を使う。この一覧は食いつきや釣り上げを保証しない。',
  acceptedBaits: 'この魚が受け付けるエサと他の釣り方を見る',
  fishProfile: '魚の詳細を開く ↗',
  mapFish: 'この魚をマップで見る ↗',
  noFish: 'この道具の魚別適合リストは確認されていません。',
  target: '選択中の魚',
  targetYes: 'この魚は道具の適合リストに含まれています。',
  targetNo: 'この魚は道具の適合リストに含まれていません。',
  targetUnknown: 'この道具には魚別の適合リストがありません。',
  assembly: '店売りセットの構成品',
  completePrice: 'セット価格',
  component: '道具の詳細を開く ↗',
  usedIn: 'この部品を含む店売りセット',
  useLocations: '入手・使用場所',
  area: (n) => `エリア${n}`,
  noUse: 'この道具の個別の使用場所は記録されていません。',
  moreOptions: '比較と別の入手方法',
  showMatches: 'この判定を通る魚を見る',
  tech: 'ROMと根拠の詳細',
  source: '研究資料',
  raw: 'ROMレコード',
  offset: 'ファイル位置',
  bytes: 'ROMレコードのバイト',
  fields: '解析済みフィールド',
  itemPrice: 'ROM内の価格欄',
  targets: '魚別応答条件',
  evidenceNotes: '技術メモ',
  openFrame: '切り抜き前の画像を開く ↗',
  sourced: '名称と実用情報は、このプロジェクトで行ったROM解析に基づきます。',
  routeReturn: '道具の詳細に戻る',
  stageWord: 'エリア',
}
