export const copy_en = {
  allItems: 'Browse all items',
  back: '← Back to where you came from',
  invalidTitle: 'Item not found',
  invalidBody: 'This item link is incomplete or its ID is not in the catalogue.',
  loadErrorTitle: 'Could not load item details',
  loadErrorBody:
    'The item data could not be loaded or displayed. Retry this page, or return to the item list.',
  retryLoad: 'Retry this page',
  backToCatalogue: 'Back to item list',
  category: 'Category',
  itemId: 'Item ID',
  use: 'What it does',
  details: 'Practical notes',
  shop: 'Where to get it',
  shopArea: (n) => `Area ${n}`,
  price: (n) => `¥${n}`,
  priceFromRom: 'ROM price field',
  stockAt: 'Recorded stock in the areas listed below',
  bundleAt: (n) => `Ready-made fly sold in area ${n}`,
  noShop: 'No shop stock for this item is recorded in the current ROM data.',
  shopMap: 'Find this shop',
  mapNote:
    'Open the shop page to see the town entrance, seller location, and recorded stock. Outdoor and town maps are shown separately.',
  unlock: 'How to unlock this offer:',
  ayuOffer:
    'Sell at least one Ayu from your keepnet to make decoy Ayu appear in the Area 3 shop. Buying it sets the stack to 9 and subtracts 9 from the sold-Ayu counter (down to 0). If it disappears, sell more Ayu before trying again.',
  unknownShopCondition:
    'This shop offer has an additional purchase condition that has not been explained yet.',
  noShopMap: 'The ROM data does not record a stage for this item’s use or sale.',
  fish: 'Fish that pass this item’s recorded check',
  fishScope: 'Passing this item check does not guarantee a bite or a landed fish.',
  routeFloat: 'Float rig',
  routeSinker: 'Sinker rig',
  floatFishHeading: 'Fish in the float-rig list',
  floatFishSummary: 'See fish for the float rig',
  floatTargetYes:
    'This profile is in the float-rig list. Float models add no fish-specific check; choose a bait this fish accepts.',
  floatTargetNo: 'This profile is not in the recorded float-rig list.',
  floatFishScope:
    'Float IDs 01–08 use the same rig check; the model adds no fish-specific bonus or restriction. The list does not guarantee a bite or landed fish.',
  sinkerFishHeading: 'Fish that pass the extra sinker-rig profile check',
  sinkerFishSummary: 'See fish for the sinker rig',
  sinkerTargetYes:
    'This profile is in the list that passes the sinker rig’s extra check. The selected bait must also pass for this fish.',
  sinkerTargetNo: 'This profile is not in the recorded sinker-rig pass list.',
  sinkerFishScope:
    'Sinker IDs 09–0A share the same extra sinker-rig profile check. This list does not establish that a bait will be eaten or a fish landed.',
  acceptedBaits: 'See bait this fish accepts and other methods',
  fishProfile: 'Open fish profile ↗',
  mapFish: 'Open this fish on the map ↗',
  noFish: 'No fish-specific compatibility list is established for this item.',
  target: 'Your selected fish',
  targetYes: 'This fish is in the item’s recorded compatible list.',
  targetNo: 'This fish is not in this item’s recorded compatible list.',
  targetUnknown: 'This item has no recorded fish compatibility list.',
  assembly: 'Shop bundle parts',
  completePrice: 'Complete set',
  component: 'Open item details ↗',
  usedIn: 'Recorded ready-made sets that include this part',
  useLocations: 'Where to obtain or use it',
  area: (n) => `Area ${n}`,
  noUse: 'No separate use location is recorded for this item.',
  moreOptions: 'More comparisons and ways to get it',
  showMatches: 'See fish that pass this check',
  tech: 'ROM and evidence details',
  source: 'Research source',
  raw: 'Raw record',
  offset: 'File offset',
  bytes: 'ROM record bytes',
  fields: 'Decoded fields',
  itemPrice: 'Price field in ROM',
  targets: 'Special response conditions',
  evidenceNotes: 'Technical notes',
  openFrame: 'Open uncropped source image ↗',
  sourced: 'Names and practical notes are based on the ROM research in this project.',
  routeReturn: 'Back to the item page',
  stageWord: 'area',
}
