export const copy_ja = {
  allItems: '道具一覧を見る',
  back: '← 前のページへ戻る',
  invalidTitle: '道具が見つかりません',
  invalidBody: '道具IDがないか、カタログに登録されていません。',
  category: 'カテゴリ',
  itemId: '道具ID',
  use: 'この道具の使い方',
  details: '使い方と注意点',
  shop: '入手場所',
  shopArea: (n) => `エリア${n}`,
  price: (n) => `${n}円`,
  priceFromRom: 'ROM内の価格欄',
  stockAt: 'このエリアの店頭記録',
  bundleAt: (n) => `エリア${n}の店売り毛バリセット`,
  noShop: '現在のROMデータでは、この道具の店頭在庫を確認できません。',
  shopMap: '販売店を見る',
  mapNote:
    '店のページで町への入口、店員の位置、在庫を確認できます。屋外と町内のマップは別々に表示します。',
  unlock: 'この品を買えるようにするには：',
  ayuOffer:
    'びくからアユを1匹以上売ると、おとりアユがエリア3の店に表示されます。購入すると所持数が9個になり、売却アユ数のカウンターが9減ります（0未満にはなりません）。表示から消えたら、追加でアユを売ってください。',
  unknownShopCondition: 'この商品には追加の購入条件がありますが、内容はまだ確認できていません。',
  noShopMap: 'ROMデータに使用・販売エリアの記録がありません。',
  fish: 'この道具の判定を通る魚',
  fishScope: 'この判定を通っても、食いつきや取り込みは保証されません。',
  routeFloat: 'ウキ仕掛け',
  routeSinker: 'オモリ仕掛け',
  fishProfile: '魚の詳細を開く ↗',
  mapFish: 'この魚をマップで見る ↗',
  noFish: 'この道具の魚別適合リストは確認されていません。',
  target: '選択中の魚',
  targetYes: 'この魚は道具の適合リストに含まれています。',
  targetNo: 'この魚は道具の適合リストに含まれていません。',
  targetUnknown: 'この道具には魚別の適合リストがありません。',
  assembly: '店売りセットの構成品',
  completePrice: 'セット価格',
  component: '道具の詳細を開く ↗',
  usedIn: 'この部品を含む店売りセット',
  useLocations: '入手・使用場所',
  area: (n) => `エリア${n}`,
  noUse: 'この道具の個別の使用場所は記録されていません。',
  moreOptions: '比較と別の入手方法',
  showMatches: 'この判定を通る魚を見る',
  tech: 'ROMと根拠の詳細',
  source: '研究資料',
  raw: 'ROMレコード',
  offset: 'ファイル位置',
  bytes: 'ROMレコードのバイト',
  fields: '解析済みフィールド',
  itemPrice: 'ROM内の価格欄',
  targets: '魚別応答条件',
  evidenceNotes: '技術メモ',
  openFrame: '切り抜き前の画像を開く ↗',
  sourced: '名称と実用情報は、このプロジェクトで行ったROM解析に基づきます。',
  routeReturn: '道具の詳細に戻る',
  stageWord: 'エリア',
}
