export const copy_en = {
  pageTitle: 'Fish profile',
  missing: 'Choose a fish from the catalogue or map.',
  invalid: 'This fish profile is not in the extracted catalogue.',
  catalogue: 'Browse fish and equipment',
  back: 'Back to previous page',
  map: 'Open this fish on the map',
  areas: 'Confirmed areas and fishing spots',
  bait: 'Live bait',
  lure: 'Lures',
  fly: 'Fly bodies',
  flyCandidates: 'Fly bodies this fish takes',
  flyProfileOnly:
    'This counts the bodies this fish takes (wet or dry). The whole fly must also get past the save’s lock: a fresh save locks body group 1 and wing group 2, and a fly matching the lock never bites. Start with the set recommended above.',
  flyBackupAction: 'Show this fish’s three-fly set',
  firstStep: 'Start with the map, then choose your gear',
  firstStepBody:
    'Choose an area to find fishing points, then choose a tackle setup below for your fishing method.',
  chooseSpots: 'Choose a fishing area',
  compatible: 'Choose bait or inspect fly candidates',
  compatibilityNote:
    'The baits and lures below are on this fish’s list: once your float or lure is on the fish’s tile it bites or chases within seconds. The fly bodies below are the bodies this fish takes, but the whole fly must also get past the save’s lock.',
  mapAction: 'Open map and fish points',
  configuredPoints: (n) => `${n} configured point${n === 1 ? '' : 's'}`,
  spawnSlots: (n) => `${n} spawn slots in the ROM table`,
  stage: (n) => `Area ${n}`,
  unknownArea:
    'No confirmed spawn locations were found for this profile in the extracted ROM location table.',
  unknownFish: (id) => `Unknown fish profile · ID ${id}`,
  unknownName: (id) => `Fish profile ${id}`,
  noSprite: 'No extracted fish portrait is available for this profile.',
  chooseArea: 'Select an area to see its map',
  float: 'Float rig',
  sinker: 'Sinker rig',
  viewItem: 'View item',
  noCompatibility: 'No compatible bait, lure, or fly body is recorded for this profile.',
  evidence: 'ROM evidence and coordinates',
  evidenceIntro:
    'The counts and locations below come from the extracted fish spawn table for the supplied Japanese ROM.',
  profile: 'Fish profile ID',
  profileOffset: 'Fish profile record offset',
  source: 'Source table',
  coords: 'Configured coordinates',
  reference: 'Compatibility sources',
  legacyName: 'Other catalogue names',
  recovery: 'Fish data could not be loaded. Retry this page or return to the catalogue.',
  retryLoad: 'Retry this fish page',
}
