export const copy_ja = {
  pageTitle: '魚の情報',
  missing: 'マップまたはカタログから魚を選んでください。',
  invalid: '抽出済みカタログにこの魚プロフィールはありません。',
  catalogue: '魚と道具の一覧',
  back: '前のページに戻る',
  map: 'この魚のマップを開く',
  areas: '確認済みエリアと釣りポイント',
  bait: 'エサ',
  lure: 'ルアー',
  fly: 'フライ本体',
  flyCandidates: 'この魚が食べるフライボディ',
  flyProfileOnly:
    'この数は魚が食べるボディ（ウェットまたはドライ）の数です。毛バリ全体がセーブのロックも通る必要があります：新規セーブはボディのグループ1とウィングのグループ2をロックし、一致する毛バリは食いつきません。まず上のおすすめセットから。',
  flyBackupAction: 'この魚の3本セットを見る',
  firstStep: 'まずマップを見てから道具を選ぶ',
  firstStepBody:
    'エリアを選んで釣りポイントを確認し、下から自分の釣り方に合う道具セットを選んでください。',
  chooseSpots: '釣るエリアを選ぶ',
  compatible: 'エサを選ぶ・フライ候補を調べる',
  compatibilityNote:
    '下のエサとルアーはこの魚のリストにあり、ウキやルアーが魚と同じマスにあれば数秒で食いつく・追ってくる。下のフライ本体はこの魚が食べるボディだが、毛バリ全体がセーブのロックも通る必要がある。',
  mapAction: 'マップと魚の位置を開く',
  configuredPoints: (n) => `設定されたポイント ${n}か所`,
  spawnSlots: (n) => `ROMテーブルの出現枠 ${n}`,
  stage: (n) => `エリア${n}`,
  unknownArea: '抽出したROM出現テーブルに確認済みの場所はありません。',
  unknownFish: (id) => `種類未特定の魚プロフィール · ID ${id}`,
  unknownName: (id) => `魚プロフィール ${id}`,
  noSprite: 'このプロフィールの魚画像は未抽出です。',
  chooseArea: 'エリアを選んでマップを表示',
  float: 'ウキ仕掛け',
  sinker: 'オモリ仕掛け',
  viewItem: 'アイテムを見る',
  noCompatibility: 'このプロフィールに対応する確認済みのエサ・ルアー・フライ本体はありません。',
  evidence: 'ROM根拠と座標',
  evidenceIntro:
    '以下の場所と数は、調査に使用した日本版ROMから抽出した魚の出現テーブルによります。',
  profile: '魚プロフィールID',
  profileOffset: '魚プロフィールのROM位置',
  source: '出現テーブル',
  coords: 'ゲーム内の設定座標',
  reference: '対応条件の資料',
  legacyName: 'カタログの別名',
  recovery: '魚データを読み込めません。このページを再読み込みするか、カタログに戻ってください。',
  retryLoad: 'この魚ページを再読み込み',
}
