export const copy_en = {
  pageTitle: 'Fish profile',
  missing: 'Choose a fish from the catalogue or map.',
  invalid: 'This fish profile is not in the extracted catalogue.',
  catalogue: 'Browse fish and equipment',
  back: 'Back to previous page',
  map: 'Open this fish on the map',
  areas: 'Confirmed areas and fishing spots',
  bait: 'Live bait',
  lure: 'Lures',
  fly: 'Fly bodies',
  firstStep: 'Start with the map, then choose your gear',
  firstStepBody:
    'Select an area below to see this fish’s ROM-derived map points and the lowest-priced compatible shop option recorded for that area. Keep compatible gear you already own. Passing the recorded check does not guarantee a bite or a landed fish.',
  chooseSpots: 'Choose a fishing area',
  compatible: 'ROM-confirmed compatibility',
  compatibilityNote:
    'These entries pass the recorded bait, lure, or fly fish check for this profile. That does not guarantee a bite or a landed catch. Rod or hook bonuses for this individual fish are not established here.',
  mapAction: 'Open map and fish points',
  configuredPoints: (n) => `${n} configured point${n === 1 ? '' : 's'}`,
  spawnSlots: (n) => `${n} spawn slots in the ROM table`,
  stage: (n) => `Area ${n}`,
  unknownArea:
    'No confirmed spawn locations were found for this profile in the extracted ROM location table.',
  unknownFish: (id) => `Unknown fish profile · ID ${id}`,
  unknownName: (id) => `Fish profile ${id}`,
  noSprite: 'No extracted fish portrait is available for this profile.',
  chooseArea: 'Select an area to see its map',
  float: 'Float rig',
  sinker: 'Sinker rig',
  viewItem: 'View item',
  noCompatibility: 'No compatible bait, lure, or fly body is recorded for this profile.',
  evidence: 'ROM evidence and coordinates',
  evidenceIntro:
    'The counts and locations below come from the extracted fish spawn table for the supplied Japanese ROM.',
  profile: 'Fish profile ID',
  profileOffset: 'Fish profile record offset',
  source: 'Source table',
  coords: 'Configured coordinates',
  reference: 'Compatibility sources',
  legacyName: 'Other catalogue names',
  recovery: 'Catalogue data could not be loaded. Return to the catalogue and try again.',
}
