export const copy_ja = {
  pageTitle: '魚の情報',
  missing: 'マップまたはカタログから魚を選んでください。',
  invalid: '抽出済みカタログにこの魚プロフィールはありません。',
  catalogue: '魚と道具の一覧',
  back: '前のページに戻る',
  map: 'この魚のマップを開く',
  areas: '確認済みエリアと釣りポイント',
  bait: 'エサ',
  lure: 'ルアー',
  fly: 'フライ本体',
  flyCandidates: 'フライ本体・プロフィール一致のみ',
  flyProfileOnly:
    'この数は魚プロフィールと一致する本体数で、判定をすべて通る完成フライ数ではありません。本体・ウィングは隠れた条件で遮断される場合があります。まず店売りセットを選び、反応しない場合は本体を全部買うのではなく予備3セットを確認してください。',
  flyBackupAction: 'この魚の予備3セットを見る',
  firstStep: 'まずマップを見てから道具を選ぶ',
  firstStepBody:
    'エリアを選んで釣りポイントを確認し、下から自分の釣り方に合う道具セットを選んでください。',
  chooseSpots: '釣るエリアを選ぶ',
  compatible: 'エサを選ぶ・フライ候補を調べる',
  compatibilityNote:
    'エサとルアーはこの魚の記録済みマスク判定を通ります。下のフライ本体は魚プロフィールとの一致のみで、完成セットの本体・ウィングには別の動的条件があります。食いつきや取り込みの保証ではありません。',
  mapAction: 'マップと魚の位置を開く',
  configuredPoints: (n) => `設定されたポイント ${n}か所`,
  spawnSlots: (n) => `ROMテーブルの出現枠 ${n}`,
  stage: (n) => `エリア${n}`,
  unknownArea: '抽出したROM出現テーブルに確認済みの場所はありません。',
  unknownFish: (id) => `種類未特定の魚プロフィール · ID ${id}`,
  unknownName: (id) => `魚プロフィール ${id}`,
  noSprite: 'このプロフィールの魚画像は未抽出です。',
  chooseArea: 'エリアを選んでマップを表示',
  float: 'ウキ仕掛け',
  sinker: 'オモリ仕掛け',
  viewItem: 'アイテムを見る',
  noCompatibility: 'このプロフィールに対応する確認済みのエサ・ルアー・フライ本体はありません。',
  evidence: 'ROM根拠と座標',
  evidenceIntro:
    '以下の場所と数は、調査に使用した日本版ROMから抽出した魚の出現テーブルによります。',
  profile: '魚プロフィールID',
  profileOffset: '魚プロフィールのROM位置',
  source: '出現テーブル',
  coords: 'ゲーム内の設定座標',
  reference: '対応条件の資料',
  legacyName: 'カタログの別名',
  recovery: '魚データを読み込めません。このページを再読み込みするか、カタログに戻ってください。',
  retryLoad: 'この魚ページを再読み込み',
}
