export const copy_en = {
  pageTitle: 'Fish profile',
  missing: 'Choose a fish from the catalogue or map.',
  invalid: 'This fish profile is not in the extracted catalogue.',
  catalogue: 'Browse fish and equipment',
  back: 'Back to previous page',
  map: 'Open this fish on the map',
  areas: 'Confirmed areas and fishing spots',
  bait: 'Live bait',
  lure: 'Lures',
  fly: 'Fly bodies',
  flyCandidates: 'Fly bodies · profile matches only',
  flyProfileOnly:
    'This count lists bodies that match the fish profile, not fully accepted fly sets. The body and wing can still fail a hidden condition. Start with a recorded shop set; if it does not get a bite, inspect the three backup sets instead of buying every body.',
  flyBackupAction: 'Show this fish’s three backup sets',
  firstStep: 'Start with the map, then choose your gear',
  firstStepBody:
    'Choose an area to find fishing points, then choose a tackle setup below for your fishing method.',
  chooseSpots: 'Choose a fishing area',
  compatible: 'Choose bait or inspect fly candidates',
  compatibilityNote:
    'Bait and lures pass this fish’s recorded mask checks. Fly bodies below only match the fish profile; the assembled body/wing set must pass another live condition. None of these checks guarantees a bite or landing.',
  mapAction: 'Open map and fish points',
  configuredPoints: (n) => `${n} configured point${n === 1 ? '' : 's'}`,
  spawnSlots: (n) => `${n} spawn slots in the ROM table`,
  stage: (n) => `Area ${n}`,
  unknownArea:
    'No confirmed spawn locations were found for this profile in the extracted ROM location table.',
  unknownFish: (id) => `Unknown fish profile · ID ${id}`,
  unknownName: (id) => `Fish profile ${id}`,
  noSprite: 'No extracted fish portrait is available for this profile.',
  chooseArea: 'Select an area to see its map',
  float: 'Float rig',
  sinker: 'Sinker rig',
  viewItem: 'View item',
  noCompatibility: 'No compatible bait, lure, or fly body is recorded for this profile.',
  evidence: 'ROM evidence and coordinates',
  evidenceIntro:
    'The counts and locations below come from the extracted fish spawn table for the supplied Japanese ROM.',
  profile: 'Fish profile ID',
  profileOffset: 'Fish profile record offset',
  source: 'Source table',
  coords: 'Configured coordinates',
  reference: 'Compatibility sources',
  legacyName: 'Other catalogue names',
  recovery: 'Catalogue data could not be loaded. Return to the catalogue and try again.',
}
