export const copy_en = {
  title: 'Kawa no Nushi Tsuri 2 — Item Catalogue & ROM Research',
  lead: 'A searchable catalogue of the game’s rods, lures, fly parts, baits, hooks, floats, food and tools—with ROM fields we could verify and clear notes where a stat is still a mystery.',
  edition: 'SFC / SNES · JAPAN VERSION',
  entries: (n) => `${n} listed entries`,
  sampleKicker: 'A FEW DECODED EXAMPLES',
  sampleTitle: 'The numbers finally have context',
  sampleCopy:
    'The ROM stores real numeric fields, but many are internal selectors rather than familiar “power” or “bite rate” stats. These examples show exact values and what the game code does with them.',
  item: 'Item',
  rom: 'ROM fields we can explain',
  price: 'ROM price field',
  flyKicker: 'THE CUSTOM FLY MAKER',
  flyTitle: 'Body, wing, tail… and a real price quote',
  flyCopy:
    'Original Japanese game captures show the verified ¥25 default recipe and ¥17 no-tail example. Choose a body for your target fish first; these examples explain menu input and price, not which fly catches best.',
  flyFact:
    'Check the final quote before paying. The recorded first-body + first-wing + first-tail Mayfly order cost ¥25. Choosing “None” changes the recipe, so read its quote separately. Other recipes do not share a fixed ¥25 price.',
  catalogueKicker: 'THE FULL INDEX',
  catalogueTitle: 'Browse all 315 listed entries',
  catalogueCopy:
    'Search either language, an item ID, or a stat. Open any card for its details, including the raw game data for anyone who wants to check.',
  search: 'Search',
  searchPlaceholder: 'Try “rod”, “トップウォータ”, or “0D”',
  category: 'Category',
  sort: 'Sort',
  all: 'All categories',
  sortId: 'Item ID',
  sortName: 'Name',
  sortPrice: 'Price in game data',
  sortBuyPrice: 'Shop availability, then price',
  results: (n) => `${n} entries shown`,
  empty: 'No matching entries. Try another name or ID.',
  noPrice: 'No price field',
  yen: '¥',
  imageNote: 'Authentic game capture',
  openFrame: 'Open full game-screen capture ↗',
  details: 'ROM record and field notes',
  offset: 'File offset',
  bytes: 'Raw bytes',
  decoded: 'Decoded fields',
  none: 'No table record supplied for this entry.',
  confidence: 'Evidence',
  japanese: 'Japanese game label',
  priceField: 'ROM price field',
  zeroPrice: '0 yen in the ROM table; not evidence that it is free or sold in a shop.',
  methodKicker: 'HOW TO READ THIS',
  methodTitle: 'Confirmed, translated, and still unknown',
  sourcesTitle: 'Sources and method',
  footer: 'Independent fan research. No ROM file is included.',
  readme: 'Project notes',
  langLink: '日本語',
  customFrames: [
    'First-stage shop: fly-family choice.',
    'Mayfly body palette.',
    'After choosing a body: wing palette.',
    'After choosing a wing: tail sprites plus a separate “None” choice.',
    'One combination quoted at ¥25.',
    'After the order was accepted.',
  ],
  quick: {
    'rod:0A':
      'Cast/aim hold-time cutoff 70; reach multiplier 15 × 336 = 5,040 internal units. Under 100 HP the cutoff scales with current HP (minimum 10).',
    'rod:0D':
      'Cast/aim hold-time cutoff 120; reach multiplier 24 × 336 = 8,064 internal units. Under 100 HP the cutoff scales with current HP (minimum 10).',
    'lure:12':
      'Action branch 9; conditional fish-ID comparison value 11 → Black bass. Changes a behavior path; does not prove an exclusive target or bonus.',
    'lure:21':
      'Action branch 7; conditional fish-ID comparison value 38 → Namazu. Changes a behavior path; does not prove an exclusive target or bonus.',
    'lure:51':
      'Action branch 5; conditional fish-ID comparison value 55 → Akame. Changes a behavior path; does not prove an exclusive target or bonus.',
    'food:01': 'Runtime-measured recovery: 5 HP.',
    'food:0A': 'Runtime-measured result: HP becomes 0.',
  },
  fieldNames: {
    styleCode: 'Rod style code',
    castAimHoldCutoffInternal: 'Cast/aim hold-time cutoff',
    rangeMultiplier: 'Reach multiplier',
    rangeInternalValueAtBase0x0150: 'Reach threshold (internal units)',
    fishIdMatchCode: 'Fish-ID comparison code',
    fightResponseCode: 'Fight-response branch selector',
    specialFishComparisonID: 'Fish-ID comparison value',
    fishHookGateMaskHex: 'Lure-hook gate mask (16 bit)',
    flyBaitMaskHex: 'Fly body acceptance mask',
  },
  noteNoJs: 'Enable JavaScript to load the searchable catalogue.',
}
