export const copy_ja = {
  title: '川のぬし釣り2 — アイテム一覧・ROM解析',
  lead: '竿、ルアー、毛バリ部品、餌、針、ウキ、食料、道具を検索できる一覧。ROMで確認できた数値と、まだ意味が分からない値を分けて掲載。',
  edition: 'SFC · 日本版',
  entries: (n) => `掲載 ${n} 件`,
  sampleKicker: '解読できた数値の例',
  sampleTitle: '数字の意味をゲーム処理と照合',
  sampleCopy:
    'ROMには数値が保存されていますが、「強さ」や「ヒット率」のような単純な能力値とは限りません。実際の値と、ゲーム内コードでの使われ方を例示します。',
  item: 'アイテム',
  rom: '意味を確認できたROM値',
  price: 'ROM価格欄',
  flyKicker: '毛バリ作成NPC',
  flyTitle: 'ボディ、ウィング、テール、そして見積もり',
  flyCopy:
    '日本版ゲームを直接撮影した画面です。ステージ1の店でメイフライ作成を最後まで進め、所持金の変化で一例の価格を確認しました。',
  flyFact:
    '確認したメイフライ画面: ウィング20種、テール画像9種と別枠の「無し」。最初のボディ+最初のウィング+最初のテールは25円（5+5+15円）。これは実測した一例で、全組み合わせ共通ではありません。',
  catalogueKicker: '全アイテム一覧',
  catalogueTitle: '掲載315件を検索',
  catalogueCopy:
    '英語・日本語、アイテムID、数値で検索できます。各カードを開くとROM生データとファイル位置を確認できます。',
  search: '検索',
  searchPlaceholder: '例: 「rod」「トップウォータ」「0D」',
  category: 'カテゴリ',
  sort: '並び順',
  all: 'すべてのカテゴリ',
  sortId: 'アイテムID',
  sortName: '名前',
  sortPrice: '価格欄',
  results: (n) => `${n}件を表示`,
  empty: '一致するアイテムはありません。名前かIDを変えてください。',
  noPrice: '価格欄なし',
  yen: '¥',
  imageNote: 'ゲーム画面から取得',
  openFrame: 'ゲーム画面全体を開く ↗',
  details: 'ROMレコードとフィールド',
  offset: 'ファイル位置',
  bytes: '生バイト列',
  decoded: '解読済みフィールド',
  none: 'この項目のテーブルレコードはありません。',
  confidence: '根拠',
  japanese: 'ゲーム内の日本語表記',
  priceField: 'ROM価格欄',
  zeroPrice: 'ROMの値は0円。無料・店頭販売を意味すると確認されたわけではありません。',
  methodKicker: '読み方',
  methodTitle: '確認済み、翻訳、未解読を区別',
  sourcesTitle: '出典と調査方法',
  footer: 'ファンによる独立調査。ROMファイルは含みません。',
  readme: 'プロジェクトノート',
  langLink: 'English',
  customFrames: [
    'ステージ1の店: 毛バリの系統選択。',
    'メイフライのボディ選択。',
    'ボディ選択後: ウィング選択。',
    'ウィング選択後: テール画像と別枠の「無し」。',
    'ある組み合わせの見積もり: 25円。',
    '注文を確定した後。',
  ],
  quick: {
    'rod:0A':
      '投げ・照準の保持時間上限70。距離判定係数15 × 336 = 内部値5,040。HP100未満ではHPに応じて上限が縮小（最低10）。',
    'rod:0D':
      '投げ・照準の保持時間上限120。距離判定係数24 × 336 = 内部値8,064。HP100未満ではHPに応じて上限が縮小（最低10）。',
    'lure:12':
      '動作分岐9。魚ID比較値11 → ブラックバス。一致時は別処理に入る。対象魚専用やボーナスとは確認されていない。',
    'lure:21':
      '動作分岐7。魚ID比較値38 → ナマズ。一致時は別処理に入る。対象魚専用やボーナスとは確認されていない。',
    'lure:51':
      '動作分岐5。魚ID比較値55 → アカメ。一致時は別処理に入る。対象魚専用やボーナスとは確認されていない。',
    'food:01': 'ゲーム内で測定した回復量: HP5。',
    'food:0A': 'ゲーム内で確認した結果: HPが0になる。',
  },
  fieldNames: {
    styleCode: '竿の釣り方コード',
    castAimHoldCutoffInternal: '投げ・照準の保持時間上限',
    rangeMultiplier: '距離判定係数',
    rangeInternalValueAtBase0x0150: '距離判定値（内部単位）',
    fishIdMatchCode: '魚ID比較コード',
    fightResponseCode: 'ファイト応答分岐',
    specialFishComparisonID: '魚ID比較値',
    fishHookGateMaskHex: '針掛かり判定マスク（16ビット）',
    flyBaitMaskHex: 'フライボディ適合マスク',
  },
  noteNoJs: '検索カタログを表示するにはJavaScriptを有効にしてください。',
}
