export const player_en = {
  title: 'Choose your next catch.',
  lead: 'Find a fish, choose compatible tackle, and see where to go.',
  menu: 'Equipment categories',
  all: 'All categories',
  fish: 'Target fish',
  allFish: 'Any fish',
  use: 'What it does',
  compatible: 'Compatible fish',
  more: 'Show all fish',
  evidence: 'Technical evidence',
  compare: 'Compare rods within a fishing style',
  aim: 'Time to aim',
  reach: 'Line strength',
  style: 'Fishing style',
  titleByCategory: 'Equipment in this category',
  noFish: 'This category is not filtered by fish species',
  fishOnly: 'Showing baits on the selected fish’s list',
  basePrice: 'Base price',
  kit: 'A lure set covering the compatible species',
  kitText:
    'Two lures cover all 38 lure fish. The guidance card and the table below list the pair you can buy complete in each area. A fish follows when it is on the lure’s tile and you keep tapping A or B; press A once when it is level with the lure to hook it.',
  kitLink: 'See the illustrated set and fish table',
  guide: 'Make a fly in the game',
  research: 'Research details and sources',
  cat: {
    rod: 'Rods',
    lure: 'Lures',
    flymaker: 'Fly maker',
    bait: 'Baits',
    hook: 'Hooks / Ayu rings',
    float_weight: 'Floats / markers / sinkers',
    food: 'Food / HP recovery',
    general_tool: 'Tools / quest items',
  },
  desc: {
    rod: 'Choose a fishing style, then compare time to aim and line strength.',
    lure: 'A fish on a lure’s list chases it when it is on the lure’s tile: keep tapping A or B, then press A once when the fish is level with the lure. Choose a fish to see its lures.',
    flymaker:
      'The body picks the fish that bite, the wing is only a ticket past the save’s hidden lock, and the tail is only looks. Open this category’s advice for the sets that work on a fresh save.',
    bait: 'A fish bites when the bait is on its list and your float is on its tile: about 2 seconds (sinker about 10 seconds, bottom fish only). Choose a fish to see its baits.',
    hook: 'Hooks and rings used by different fishing styles.',
    float_weight: 'Floats, line markers and sinkers.',
    food: 'Measured recovery and food that drains HP.',
    general_tool:
      'How to use each tool, its effects, and location or quest conditions traced from game code.',
  },
}
