export const player_en = {
  title: 'Choose your next catch.',
  lead: 'Find a fish, choose compatible tackle, and see where to go.',
  menu: 'Equipment categories',
  all: 'All categories',
  fish: 'Target fish',
  allFish: 'Any fish',
  use: 'What it does',
  compatible: 'Compatible fish',
  more: 'Show all fish',
  evidence: 'Technical evidence',
  compare: 'Compare rods within a fishing style',
  aim: 'Time to aim',
  reach: 'Line strength',
  style: 'Fishing style',
  titleByCategory: 'Equipment in this category',
  noFish: 'This category is not filtered by fish species',
  fishOnly: 'Showing baits that pass the selected fish’s conditions',
  basePrice: 'Base price',
  kit: 'A lure set covering the compatible species',
  kitText:
    'Choose by area: Spoon 2E + Soft worm 23 costs ¥55 in Area 1, Sinking lure 17 + Soft worm 24 costs ¥55 in Areas 2–3, and Sinking lure 17 + Soft worm 23 costs ¥50 in Area 4. Areas 5–6 sell no complete pair; carry one you own or buy Sinking lure 17 + Soft worm 23 in Area 4. Each pair covers the same 38 lure-compatible profiles, not a guaranteed bite or catch.',
  kitLink: 'See the illustrated set and fish table',
  guide: 'Make a fly in the game',
  research: 'Research details and sources',
  cat: {
    rod: 'Rods',
    lure: 'Lures',
    flymaker: 'Fly maker',
    bait: 'Baits',
    hook: 'Hooks / Ayu rings',
    float_weight: 'Floats / markers / sinkers',
    food: 'Food / HP recovery',
    general_tool: 'Tools / quest items',
  },
  desc: {
    rod: 'Choose a fishing style, then compare time to aim and line strength.',
    lure: 'Choose a target fish to filter lures by the hook-acceptance condition.',
    flymaker: 'Browse bodies, wings and tails, with conditions that affect hooking.',
    bait: 'Choose a fish to see baits that pass the bait-mode conditions.',
    hook: 'Hooks and rings used by different fishing styles.',
    float_weight: 'Floats, line markers and sinkers.',
    food: 'Measured recovery and food that drains HP.',
    general_tool:
      'How to use each tool, its effects, and location or quest conditions traced from game code.',
  },
}
